Reverting.

diff --git a/server/node-init/init.d/codebounty b/server/node-init/init.d/codebounty
--- a/server/node-init/init.d/codebounty
+++ b/server/node-init/init.d/codebounty
@@ -1,42 +1,60 @@
-#! /bin/sh
+#! /bin/bash
+
 ### BEGIN INIT INFO
 # Provides:          codebounty
 # Required-Start:    $remote_fs $named $syslog
 # Required-Stop:     $remote_fs $named $syslog
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
-# Short-Description: Codebounty node server initscript
+# Short-Description: codebounty server
 ### END INIT INFO
 
-# Author: Kaiwen Xu <kevin@kevxu.net>
+PATH=/sbin:/usr/sbin:/bin:/usr/bin:/opt/node/default/bin
+DAEMON_ARGS="/srv/codebounty/deployed/main.js"
+DESC="codebounty server"
+NODEUSER=codebounty:codebounty
+LOCAL_VAR_RUN=/var/run
+CHDIR="/srv/codebounty/deployed"
+NAME=node
+DAEMON=/opt/node/default/bin/$NAME
+LOGFILE=/var/log/codebounty.log
+
 
 # Do NOT "set -e"
 
-# PATH should only include /usr/* if it runs after the mountnfs.sh script
-PATH=/sbin:/usr/sbin:/bin:/usr/bin:/opt/node/default/bin
-DESC="Codebounty server"
-NAME=node
-DAEMON=/opt/node/default/bin/$NAME
-DAEMON_ARGS="/srv/codebounty/deployed/main.js"
-PIDFILE=/var/run/$NAME.pid
-SCRIPTNAME=/etc/init.d/$NAME
-CHUID=codebounty:codebounty
-CHDIR="/srv/codebounty/deployed"
 NCMD="exec $DAEMON $DAEMON_ARGS >>$LOGFILE 2>&1"
 
+if [ ! -e "$LOGFILE" ]; then
+        touch "$LOGFILE"
+        chown $NODEUSER "$LOGFILE"
+fi
+
+[ $UID -eq "0" ] && LOCAL_VAR_RUN=/var/run # in case this script is run by root, override user setting
+THIS_ARG=$0
+INIT_SCRIPT_NAME=`basename $THIS_ARG`
+[ -h $THIS_ARG ] && INIT_SCRIPT_NAME=`basename $(readlink $THIS_ARG)` # in case of symlink
+INIT_SCRIPT_NAME_NOEXT=${INIT_SCRIPT_NAME%.*}
+PIDFILE="$LOCAL_VAR_RUN/$INIT_SCRIPT_NAME_NOEXT.pid"
+SCRIPTNAME=/etc/init.d/$INIT_SCRIPT_NAME
+
 # Exit if the package is not installed
-[ -x "$DAEMON" ] || exit 0
+[ -x "$DAEMON" ] ||  { echo "can't find Node.js ($DAEMON)"  >&2; exit 0; }
+
+# Exit if the 'run' folder is not present
+[ -d "$LOCAL_VAR_RUN" ] || { echo "Directory $LOCAL_VAR_RUN does not exist. Modify the '$INIT_SCRIPT_NAME_NOEXT' init.d script ($THIS_ARG) accordingly" >&2; exit 0; }
 
 # Read configuration variable file if it is present
-[ -r /etc/default/$NAME ] && . /etc/default/$NAME
+[ -r /etc/default/$INIT_SCRIPT_NAME ] && . /etc/default/$INIT_SCRIPT_NAME
 
 # Load the VERBOSE setting and other rcS variables
 . /lib/init/vars.sh
 
 # Define LSB log_* functions.
-# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
-# and status_of_proc is working.
+# Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
 . /lib/lsb/init-functions
+
+# uncomment to override system setting
+VERBOSE=yes
 
 #
 # Function that starts the daemon/service
@@ -47,15 +65,14 @@ do_start()
     #   0 if daemon has been started
     #   1 if daemon was already running
     #   2 if daemon could not be started
-    start-stop-daemon --start --quiet --pidfile $PIDFILE --chdir $CHDIR --chuid $CHUID \
-        --exec $DAEMON --test > /dev/null \
-        || return 1
-    start-stop-daemon --start --quiet --chdir $CHDIR --chuid $CHUID --make-pidfile \
-        --pidfile $PIDFILE --background --exec $DAEMON --startas /bin/sh -- -c "$NCMD" \
-        || return 2
+    start-stop-daemon --start --quiet --chdir $CHDIR --pidfile $PIDFILE --chuid $NODEUSER --background --exec $DAEMON --test > /dev/null \
+        || { [ "$VERBOSE" != no ] && log_daemon_msg  "  --->  Daemon already running $DESC" "$INIT_SCRIPT_NAME_NOEXT"; return 1; }
+    start-stop-daemon --start --quiet --chdir $CHDIR --chuid $NODEUSER --make-pidfile --pidfile $PIDFILE --background --exec $DAEMON --startas /bin/sh -- -c "$NCMD" \
+        || { [ "$VERBOSE" != no ] && log_daemon_msg  "  --->  could not be start $DESC" "$INIT_SCRIPT_NAME_NOEXT"; return 2; }
     # Add code here, if necessary, that waits for the process to be ready
     # to handle requests from services started subsequently which depend
     # on this one.  As a last resort, sleep for some time.
+    [ "$VERBOSE" != no ] && log_daemon_msg  "  --->  started $DESC" "$INIT_SCRIPT_NAME_NOEXT"
 }
 
 #
@@ -68,8 +85,9 @@ do_stop()
     #   1 if daemon was already stopped
     #   2 if daemon could not be stopped
     #   other if a failure occurred
-    start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $NAME
+    start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE  --chuid $NODEUSER --exec $DAEMON
     RETVAL="$?"
+    #[ "$VERBOSE" != no ] && [ "$RETVAL" = 1 ] && log_daemon_msg  "  --->  SIGKILL failed => hardkill $DESC" "$INIT_SCRIPT_NAME_NOEXT"
     [ "$RETVAL" = 2 ] && return 2
     # Wait for children to finish too if this is a daemon that forks
     # and if the daemon is only ever run from this initscript.
@@ -77,10 +95,12 @@ do_stop()
     # that waits for the process to drop all resources that could be
     # needed by services started subsequently.  A last resort is to
     # sleep for some time.
-    start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --exec $DAEMON
+    start-stop-daemon --stop --quiet --oknodo --retry=0/3/KILL/5 --pidfile $PIDFILE  --chuid $NODEUSER --exec $DAEMON -- $DAEMON_ARGS
     [ "$?" = 2 ] && return 2
     # Many daemons don't delete their pidfiles when they exit.
     rm -f $PIDFILE
+  [ "$VERBOSE" != no ] && [ "$RETVAL" = 1 ] && log_daemon_msg "  --->  $DESC not running" "$INIT_SCRIPT_NAME_NOEXT"
+  [ "$VERBOSE" != no -a "$RETVAL" = 0 ] && log_daemon_msg "  --->  $DESC stopped" "$INIT_SCRIPT_NAME_NOEXT"
     return "$RETVAL"
 }
 
@@ -93,13 +113,56 @@ do_reload() {
     # restarting (for example, when it is sent a SIGHUP),
     # then implement that here.
     #
-    start-stop-daemon --stop --signal 1 --quiet --pidfile $PIDFILE --chuid $CHUID --name $NAME
+    start-stop-daemon --stop --quiet --signal 1 --pidfile $PIDFILE  --chuid $NODEUSER --name $NAME
     return 0
 }
 
+#
+# Function that returns the daemon
+#
+do_status() {
+  #
+  # http://refspecs.freestandards.org/LSB_3.1.1/LSB-Core-generic/LSB-Core-generic/iniscrptact.html
+  # 0 program is running or service is OK
+  # 1 program is dead and /var/run pid file exists
+  # (2 program is dead and /var/lock lock file exists) (not used here)
+  # 3 program is not running
+  # 4 program or service status is unknown
+  RUNNING=$(running)
+
+  # $PIDFILE corresponds to a live $NAME process
+  ispidactive=$(pidof $NAME | grep `cat $PIDFILE 2>&1` >/dev/null 2>&1)
+  ISPIDACTIVE=$?
+
+  if [ -n "$RUNNING" ]; then
+    if [ $ISPIDACTIVE ]; then
+      log_success_msg "$INIT_SCRIPT_NAME_NOEXT (launched by $USER) (--chuid $NODEUSER) is running"
+      exit 0
+    fi
+  else
+    if [ -f $PIDFILE ]; then
+      log_success_msg "$INIT_SCRIPT_NAME_NOEXT (launched by $USER) (--chuid $NODEUSER) is not running, phantom pidfile $PIDFILE"
+      exit 1
+    else
+      log_success_msg "no instance launched by $USER, of $INIT_SCRIPT_NAME_NOEXT (--chuid $NODEUSER) found"
+      exit 3
+    fi
+  fi
+
+}
+
+running() {
+  RUNSTAT=$(start-stop-daemon --start --quiet --pidfile $PIDFILE --chuid $NODEUSER --background --exec $DAEMON --test > /dev/null)
+  if [ "$?" = 1 ]; then
+    echo y
+  fi
+
+}
+
+
 case "$1" in
   start)
-    [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
+    [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$INIT_SCRIPT_NAME_NOEXT"
     do_start
     case "$?" in
         0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
@@ -107,15 +170,12 @@ case "$1" in
     esac
     ;;
   stop)
-    [ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
+    [ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$INIT_SCRIPT_NAME_NOEXT"
     do_stop
     case "$?" in
         0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
         2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
     esac
-    ;;
-  status)
-    status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
     ;;
   #reload|force-reload)
     #
@@ -131,7 +191,7 @@ case "$1" in
     # If the "reload" option is implemented then remove the
     # 'force-reload' alias
     #
-    log_daemon_msg "Restarting $DESC" "$NAME"
+    log_daemon_msg "Restarting $DESC" "$INIT_SCRIPT_NAME_NOEXT"
     do_stop
     case "$?" in
       0|1)
@@ -148,11 +208,14 @@ case "$1" in
         ;;
     esac
     ;;
+  status)
+    do_status
+  ;;
   *)
     #echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
-    echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
+    echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload}" >&2
     exit 3
     ;;
 esac
 
-:
+exit 0
