Switch production server to using forever.

diff --git a/server/etc/init.d/codebounty b/server/etc/init.d/codebounty
--- a/server/etc/init.d/codebounty
+++ b/server/etc/init.d/codebounty
@@ -10,7 +10,9 @@
 ### END INIT INFO
 
 PATH=/sbin:/usr/sbin:/bin:/usr/bin:/opt/node/default/bin
-DAEMON_ARGS="/srv/codebounty/deployed/main.js"
+HOME=/home/codebounty
+MAIN_SCRIPT="/srv/codebounty/deployed/main.js"
+DAEMON_ARGS="/opt/node/default/bin/forever --plain -c '/opt/node/default/bin/node' $MAIN_SCRIPT"
 DESC="codebounty server"
 NODEUSER=codebounty:codebounty
 LOCAL_VAR_RUN=/var/run
@@ -67,9 +69,11 @@ do_start()
 	#   0 if daemon has been started
 	#   1 if daemon was already running
 	#   2 if daemon could not be started
-	start-stop-daemon --start --quiet --chdir $CHDIR --pidfile $PIDFILE --chuid $NODEUSER --background --exec $DAEMON --test > /dev/null \
+	start-stop-daemon --start --quiet --chdir $CHDIR --chuid $NODEUSER \
+		--pidfile $PIDFILE --background --exec $DAEMON --test > /dev/null \
 		|| return 1
-	start-stop-daemon --start --quiet --chdir $CHDIR --chuid $NODEUSER --make-pidfile --pidfile $PIDFILE --background --exec $DAEMON --startas /bin/sh -- -c "$NCMD" \
+	start-stop-daemon --start --quiet --chdir $CHDIR --chuid $NODEUSER \
+		--make-pidfile --pidfile $PIDFILE --background --exec $DAEMON --startas /bin/sh -- -c "$NCMD" \
 		|| return 2
 }
 
@@ -83,75 +87,78 @@ do_stop()
 	#   1 if daemon was already stopped
 	#   2 if daemon could not be stopped
 	#   other if a failure occurred
-	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE  --chuid $NODEUSER --exec $DAEMON
-	RETVAL="$?"
+	# start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE \
+	# 	--chuid $NODEUSER --exec $DAEMON
+	# RETVAL="$?"
 	#[ "$VERBOSE" != no ] && [ "$RETVAL" = 1 ] && log_daemon_msg  "  --->  SIGKILL failed => hardkill $DESC" "$INIT_SCRIPT_NAME_NOEXT"
-	[ "$RETVAL" = 2 ] && return 2
+	# [ "$RETVAL" = 2 ] && return 2
 	# Wait for children to finish too if this is a daemon that forks
 	# and if the daemon is only ever run from this initscript.
 	# If the above conditions are not satisfied then add some other code
 	# that waits for the process to drop all resources that could be
 	# needed by services started subsequently.  A last resort is to
 	# sleep for some time.
-	start-stop-daemon --stop --quiet --oknodo --retry=0/3/KILL/5 --pidfile $PIDFILE  --chuid $NODEUSER --exec $DAEMON -- $DAEMON_ARGS
+	# start-stop-daemon --stop --quiet --oknodo --retry=0/3/KILL/5 --pidfile $PIDFILE \
+	# 	--chuid $NODEUSER --exec $DAEMON -- $DAEMON_ARGS
+	sudo -u codebounty PATH=$PATH:/opt/node/default/bin HOME=/home/codebounty /opt/node/default/bin/forever stop $MAIN_SCRIPT
 	[ "$?" = 2 ] && return 2
 	# Many daemons don't delete their pidfiles when they exit.
 	rm -f $PIDFILE
-	return "$RETVAL"
+	return "$?"
 }
 
 #
 # Function that sends a SIGHUP to the daemon/service
 #
-do_reload() {
+# do_reload() {
 	#
 	# If the daemon can reload its configuration without
 	# restarting (for example, when it is sent a SIGHUP),
 	# then implement that here.
 	#
-	start-stop-daemon --stop --quiet --signal 1 --pidfile $PIDFILE  --chuid $NODEUSER --name $NAME
-	return 0
-}
+	# start-stop-daemon --stop --quiet --signal 1 --pidfile $PIDFILE  --chuid $NODEUSER --name $NAME
+	# return 0
+# }
 
 #
 # Function that returns the daemon
 #
-do_status() {
-	#
-	# http://refspecs.freestandards.org/LSB_3.1.1/LSB-Core-generic/LSB-Core-generic/iniscrptact.html
-	# 0 program is running or service is OK
-	# 1 program is dead and /var/run pid file exists
-	# (2 program is dead and /var/lock lock file exists) (not used here)
-	# 3 program is not running
-	# 4 program or service status is unknown
-	RUNNING=$(running)
+# do_status() {
+# 	#
+# 	# http://refspecs.freestandards.org/LSB_3.1.1/LSB-Core-generic/LSB-Core-generic/iniscrptact.html
+# 	# 0 program is running or service is OK
+# 	# 1 program is dead and /var/run pid file exists
+# 	# (2 program is dead and /var/lock lock file exists) (not used here)
+# 	# 3 program is not running
+# 	# 4 program or service status is unknown
+# 	RUNNING=$(running)
 
-	# $PIDFILE corresponds to a live $NAME process
-	ispidactive=$(pidof $NAME | grep `cat $PIDFILE 2>&1` >/dev/null 2>&1)
-	ISPIDACTIVE=$?
+# 	# $PIDFILE corresponds to a live $NAME process
+# 	ispidactive=$(pidof $NAME | grep `cat $PIDFILE 2>&1` >/dev/null 2>&1)
+# 	ISPIDACTIVE=$?
 
-	if [ -n "$RUNNING" ]; then
-		if [ $ISPIDACTIVE ]; then
-			log_success_msg "$INIT_SCRIPT_NAME_NOEXT (launched by $USER) (--chuid $NODEUSER) is running"
-			exit 0
-		fi
-	else
-		if [ -f $PIDFILE ]; then
-			log_success_msg "$INIT_SCRIPT_NAME_NOEXT (launched by $USER) (--chuid $NODEUSER) is not running, phantom pidfile $PIDFILE"
-			exit 1
-		else
-			log_success_msg "no instance launched by $USER, of $INIT_SCRIPT_NAME_NOEXT (--chuid $NODEUSER) found"
-			exit 3
-		fi
-	fi
-}
+# 	if [ -n "$RUNNING" ]; then
+# 		if [ $ISPIDACTIVE ]; then
+# 			log_success_msg "$INIT_SCRIPT_NAME_NOEXT (launched by $USER) (--chuid $NODEUSER) is running"
+# 			exit 0
+# 		fi
+# 	else
+# 		if [ -f $PIDFILE ]; then
+# 			log_success_msg "$INIT_SCRIPT_NAME_NOEXT (launched by $USER) (--chuid $NODEUSER) is not running, phantom pidfile $PIDFILE"
+# 			exit 1
+# 		else
+# 			log_success_msg "no instance launched by $USER, of $INIT_SCRIPT_NAME_NOEXT (--chuid $NODEUSER) found"
+# 			exit 3
+# 		fi
+# 	fi
+# }
 
-running() {
-	RUNSTAT=$(start-stop-daemon --start --quiet --pidfile $PIDFILE --chuid $NODEUSER --background --exec $DAEMON --test > /dev/null)
-	if [ "$?" = 1 ]; then
-		echo y
-	fi
-}
+# running() {
+# 	RUNSTAT=$(start-stop-daemon --start --quiet --pidfile $PIDFILE --chuid $NODEUSER --background --exec $DAEMON --test > /dev/null)
+# 	if [ "$?" = 1 ]; then
+# 		echo y
+# 	fi
+# }
 
 
 case "$1" in
@@ -202,9 +209,9 @@ case "$1" in
 			;;
 		esac
 		;;
-	status)
-		do_status
-		;;
+	# status)
+	# 	do_status
+	# 	;;
 	*)
 		#echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
 		echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload}" >&2
